import java.io.InputStream;

public class mResources {
   public int[] imgId = new int[3];
   public static String nameHienThi;
   public static int[] listPort;
   public static String[] listIP;
   public static int[] serverST;
   public static String[] listName;
   public static byte[] serverLoginList;
   public static int languageID;
   public static String gameAI;
   public static String gameAJ;
   public static String gameAK;
   public static String gameAL;
   public static String gameAM;
   public static String gameAN;
   public static String gameAO;
   public static String gameAP;
   public static String gameAQ;
   public static String gameAR;
   public static String gameAS;
   public static String gameAT;
   public static String gameAU;
   public static String gameAV;
   public static String gameAW;
   public static String gameAX;
   public static String gameAY;
   public static String gameAZ;
   public static String gameBA;
   public static String gameBB;
   public static String gameBC;
   public static String gameBD;
   public static String gameBE;
   public static String[] tips;
   public static String gameBG;
   public static String gameBH;
   public static String gameBI;
   public static String gameBJ;
   public static String gameBK;
   public static String LANGUAGE;
   public static String gameBM;
   public static String[] LANGUAGES;
   public static String gameBO;
   public static String CLOSE;
   public static String gameBQ;
   public static String gameBR;
   public static String gameBS;
   public static String gameBT;
   public static String gameBU;
   public static String gameBV;
   public static String gameBW;
   public static String gameBX;
   public static String gameBY;
   public static String gameBZ;
   public static String gameCA;
   public static String gameCB;
   public static String gameCC;
   public static String gameCD;
   public static String DELETE;
   public static String gameCF;
   public static String gameCG;
   public static String gameCH;
   public static String gameCI;
   public static String gameCJ;
   public static String gameCK;
   public static String gameCL;
   public static String gameCM;
   public static String gameCN;
   public static String gameCO;
   public static String YES;
   public static String gameCQ;
   public static String gameCR;
   public static String gameCS;
   public static String gameCT;
   public static String gameCU;
   public static String gameCV;
   public static String gameCW;
   public static String gameCX;
   public static String gameCY;
   public static String gameCZ;
   public static String gameDA;
   public static String gameDB;
   public static String NO;
   public static String EXIT;
   public static String CHAT;
   public static String OK;
   public static String USERNAME;
   public static String PASSWORD;
   public static String REPASS;
   public static String gameDJ;
   public static String gameDK;
   public static String gameDL;
   public static String RESTART;
   public static String REPASSWORD;
   public static String REMEMBER;
   public static String UNCHECK;
   public static String gameDQ;
   public static String gameDR;
   public static String gameDS;
   public static String NOT_INPUT_USERNAME;
   public static String NOT_SPEC_CHARACTER;
   public static String NOT_INPUT_PASS1;
   public static String NOT_INPUT_PASS2;
   public static String USERNAME_LENGHT;
   public static String WRONG_PASSWORD;
   public static String[] REGISTER_TEXT;
   public static String gameEA;
   public static String ASK_REG_NUM;
   public static String gameEC;
   public static String[] gameED;
   public static String gameEE;
   public static String gameEF;
   public static String gameEG;
   public static String gameEH;
   public static String ACCEPT;
   public static String CANCEL;
   public static String gameEK;
   public static String gameEL;
   public static String gameEM;
   public static String gameEN;
   public static String gameEO;
   public static String CONNECTING;
   public static String REGISTERING;
   public static String LOGGING;
   public static String gameES;
   public static String gameET;
   public static String gameEU;
   public static String SELECT;
   public static String gameEW;
   public static String gameEX;
   public static String gameEY;
   public static String gameEZ;
   public static String gameFA;
   public static String gameFB;
   public static String gameFC;
   public static String gameFD;
   public static String gameFE;
   public static String gameFF;
   public static String gameFG;
   public static String CHARNAME;
   public static String gameFI;
   public static String gameFJ;
   public static String gameFK;
   public static String gameFL;
   public static String gameFM;
   public static String gameFN;
   public static String gameFO;
   public static String gameFP;
   public static String gameFQ;
   public static String gameFR;
   public static String gameFS;
   public static String gameFT;
   public static String gameFU;
   public static String gameFV;
   public static String gameFW;
   public static String[] gameFX;
   public static String gameFY;
   public static String gameFZ;
   public static String gameGA;
   public static String gameGB;
   public static String gameGC;
   public static String gameGD;
   public static String gameGE;
   public static String gameGF;
   public static String gameGG;
   public static String CHANGE;
   public static String gameGI;
   public static String gameGJ;
   public static String[] gameGK;
   public static String[] gameGL;
   public static String[][] HAIR_STYLE;
   public static String[] gameGN;
   public static String[] gameGO;
   public static String[] gameGP;
   public static String[] gameGQ;
   public static String[] gameGR;
   public static String[] gameGS;
   public static String[] gameGT;
   public static String[] gameGU;
   public static String[] gameGV;
   public static String[] gameGW;
   public static String[] gameGX;
   public static String[] gameGY;
   public static String[] gameGZ;
   public static String[] gameHA;
   public static String[] gameHB;
   public static String[] gameHC;
   public static String[] gameHD;
   public static String[] gameHE;
   public static String[] gameHF;
   public static String[] gameHG;
   public static String[] gameHH;
   public static String[] gameHI;
   public static String[] gameHJ;
   public static String[] gameHK;
   public static String[] gameHL;
   public static String[] gameHM;
   public static String[] gameHN;
   public static String[] gameHO;
   public static String[] gameHP;
   public static String[] gameHQ;
   public static String[] gameHR;
   public static String[] gameHS;
   public static String[] gameHT;
   public static String[] gameHU;
   public static String[] gameHV;
   public static String[] gameHW;
   public static String gameHX;
   public static String gameHY;
   public static String gameHZ;
   public static String gameKA;
   public static String gameKB;
   public static String gameKC;
   public static String gameKD;
   public static String gameKE;
   public static String gameKF;
   public static String gameKG;
   public static String gameKH;
   public static String gameKI;
   public static String gameKJ;
   public static String gameKK;
   public static String gameKL;
   public static String gameKM;
   public static String gameKN;
   public static String gameKO;
   public static String gameKP;
   public static String gameKQ;
   public static String gameKR;
   public static String gameKS;
   public static String gameKT;
   public static String gameKU;
   public static String gameKV;
   public static String gameKW;
   public static String gameKX;
   public static String gameKY;
   public static String gameKZ;
   public static String gameMA;
   public static String[] gameMB;
   public static String ME_TASK;
   public static String gameMD;
   public static String gameME;
   public static String gameMF;
   public static String gameMG;
   public static String gameMH;
   public static String gameMI;
   public static String gameMJ;
   public static String[] gameMK;
   public static String gameML;
   public static String gameMM;
   public static String gameMN;
   public static String gameMO;
   public static String gameMP;
   public static String gameMQ;
   public static String[] gameMR;
   public static String[] gameMS;
   public static String[] gameMT;
   public static String gameMU;
   public static String[] gameMV;
   public static String[] gameMW;
   public static String[] gameMX;
   public static String[] MENUGENDER;
   public static String[] gameMZ;
   public static String gameNA;
   public static String gameNB;
   public static String gameNC;
   public static String gameND;
   public static String[] gameNE;
   public static String gameNF;
   public static String gameNG;
   public static String gameNH;
   public static String gameNI;
   public static String gameNJ;
   public static String gameNK;
   public static String gameNL;
   public static String gameNM;
   public static String gameNN;
   public static String gameNO;
   public static String gameNP;
   public static String gameNQ;
   public static String gameNR;
   public static String gameNS;
   public static String gameNT;
   public static String gameNU;
   public static String gameNV;
   public static String gameNW;
   public static String gameNX;
   public static String gameNY;
   public static String gameNZ;
   public static String gamePA;
   public static String gamePB;
   public static String gamePC;
   public static String INPUT_NICK;
   public static String gamePE;
   public static String gamePF;
   public static String gamePG;
   public static String gamePH;
   public static String gamePI;
   public static String gamePJ;
   public static String gamePK;
   public static String gamePL;
   public static String gamePM;
   public static String[][] gamePN;
   public static String[] gamePO;
   public static String[] gamePP;
   public static String gamePQ;
   public static String gamePR;
   public static String gamePS;
   public static String gamePT;
   public static String gamePU;
   public static String gamePV;
   public static String gamePW;
   public static String[] gamePX;
   public static String[] gamePY;
   public static String MONTH;
   public static String WEEK;
   public static String DAY;
   public static String HOUR;
   public static String gameQD;
   public static String MINUTE;
   public static String gameQF;
   public static String gameQG;
   public static String gameQH;
   public static String gameQI;
   public static String gameQJ;
   public static String gameQK;
   public static String gameQL;
   public static String gameQM;
   public static String gameQN;
   public static String gameQO;
   public static String gameQP;
   public static String gameQQ;
   public static String gameQR;
   public static String gameQS;
   public static String gameQT;
   public static String gameQU;
   public static String gameQV;
   public static String gameQW;
   public static String gameQX;
   public static String gameQY;
   public static String gameQZ;
   public static String gameRA;
   public static String gameRB;
   public static String gameRC;
   public static String gameRD;
   public static String gameRE;
   public static String gameRF;
   public static String[] gameRG;
   public static String gameRH;
   public static String gameRI;
   public static String gameRJ;
   public static String gameRK;
   public static String gameRL;
   public static String[] gameRM;
   public static String[] gameRN;
   public static String[] CLAN_ACTIVITY;
   public static String gameRP;
   public static String gameRQ;
   public static String[][] gameRR;
   public static String[] gameRS;
   public static String[] gameRT;
   public static String[] gameRU;
   public static String[] CHARINGFO;
   public static String gameRW;
   public static String gameRX;
   public static String gameRY;
   public static String gameRZ;
   public static String gameSA;
   public static String gameSB;
   public static String gameSC;
   public static String gameSD;
   public static String gameSE;
   public static String gameSF;
   public static String[] gameSG;
   public static String gameSH;
   public static String[] gameSI;
   public static String[] gameSJ;
   public static String gameSK;
   public static String gameSL;
   public static String gameSM;
   public static String gameSN;
   public static String gameSO;
   public static String gameSP;
   public static String gameSQ;
   public static String gameSR;
   public static String gameSS;
   public static String gameST;
   public static String gameSU;
   public static String[] gameSV;
   public static String[] gameSW;
   public static String[] gameSX;
   public static String[] gameSY;
   public static String[] gameSZ;
   public static String[] gameTA;
   public static String gameTB;
   public static String[] gameTC;
   public static String gameTD;
   public static String gameTE;
   public static String gameTF;
   public static String gameTG;
   public static String gameTH;
   public static String gameTI;
   public static String[] gameTJ;
   public static String[] gameTK;
   public static String[] gameTL;
   public static String CLOSE_CURTAB;
   public static String[] PUBLICCHAT;
   public static String[] PARTYCHAT;
   public static String[] GLOBALCHAT;
   public static String[] CLANCHAT;
   public static String gameTR;
   public static String gameTS;
   public static String gameTT;
   public static String gameTU;
   public static String gameTV;
   public static String gameTW;
   public static String gameTX;
   public static String gameTY;
   public static String gameTZ;
   public static String gameUA;
   public static String gameUB;
   public static String gameUC;
   public static String gameUD;
   public static String gameUE;
   public static String gameUF;
   public static String gameUG;
   public static String gameUH;
   public static String gameUI;
   public static String gameUJ;
   public static String gameUK;
   public static String gameUL;
   public static String gameUM;
   public static String gameUN;
   public static String gameUO;
   public static String gameUP;
   public static String gameUQ;
   public static String gameUR;
   public static String gameUS;
   public static String gameUT;
   public static String gameUU;
   public static String gameUV;
   public static String gameUW;
   public static String[] gameUX;
   public static String gameUY;
   public static String gameUZ;
   public static String gameVA;
   public static String gameVB;
   public static String gameVC;
   public static String gameVD;
   public static String gameVE;
   public static String gameVF;
   public static String gameVG;
   public static String gameVH;
   public static String gameVI;
   public static String gameVJ;
   public static String gameVK;
   public static String gameVL;
   public static String gameVM;
   public static String gameVN;
   public static String gameVO;
   public static String gameVP;
   public static String gameVQ;
   public static String gameVR;
   public static String[] gameVS;
   public static String gameVT;
   public static String gameVU;
   public static String gameVV;
   public static String gameVW;
   public static String gameVX;
   public static String gameVY;
   public static String gameVZ;
   public static String gameWA;
   public static String gameWB;
   public static String gameWC;
   public static String[][] gameWD;
   public static String[] gameWE;
   public static String gameWF;
   public static String gameWG;
   public static String gameWH;
   public static String gameWI;
   public static String[] gameWJ;
   public static String[] gameWK;
   public static String gameWL;
   public static String gameWM;
   public static String gameWN;
   public static String[] gameWO;
   public static String gameWP;
   public static String gameWQ;
   public static String gameWR;
   public static String gameWS;
   public static String gameWT;
   public static String gameWU;
   public static String gameWV;
   public static String gameWW;
   public static String gameWX;
   public static String gameWY;
   public static String gameWZ;
   public static String gameXA;
   public static String gameXB;
   public static String gameXC;
   public static String gameXD;
   public static String gameXE;
   public static String[] gameXF;
   public static String gameXG;
   public static String NEW_ACC_ARLET;
   public static String NEW_PLAY;
   public static String COUNTINUE_PLAY;
   public static String CHANGE_ACC;
   public static String SERVER;
   public static String COUNTINUE;
   public static String[] gameXN;
   public static String gameXO;
   public static String gameXP;
   public static String gameXK;

   public static void gameAA() {
      String var0 = gameAA("hd.txt");
      GameScr.gI().gameAA("Hướng dẫn", var0, false);
   }

   private static String gameAA(String var0) {
      InputStream var3 = RMS.gameAA("/" + var0);

      try {
         byte[] var1 = new byte[var3.available()];
         var3.read(var1);
         var0 = new String(var1, "UTF-8");
      } catch (Exception var2) {
         var0 = "";
      }

      return var0;
   }

   public static void gameAB() {
      String[] var10000;
      if (languageID == 0) {
         gameXK = "Cập nhật máy chủ";
         gameAJ = "Viên ngọc này không thể gọt.";
         gameAI = "Viên ngọc đã đạt cấp độ tối đa.";
         gameAK = "Đăng ký một tài khoản sẽ giúp nhân vật đang chơi của bạn còn mãi. Bạn có muốn đăng ký không?";
         gameAL = "Nhiệm vụ bí ẩn";
         gameAM = "- Nâng hiếu chiến lên 1.";
         gameAN = "- Hoàn thành hang động 1 lần.";
         gameAO = "- Hoàn thành tà thú 1 lần.";
         gameAP = "- Hoàn thành 1 lần nâng cấp.";
         gameAQ = "- Hoàn thành 10 nhiệm vụ hàng ngày.";
         gameAR = "- Lấy 1000 điểm chiến trường.";
         gameAS = "- Hoàn thành 1 lần thất thú ải.";
         gameAT = "- Hoàn thành 3 lần quay số.";
         var10000 = new String[]{"Katana", "Bokken", "Shuriken", "Tessen", "Kunai", "Liên Server"};
         gameAW = "Tỉ lệ thắng";
         gameAX = "Bạn đã tham gia: ";
         gameAY = "Số người tham gia: ";
         gameAZ = "Vòng xoay may mắn";
         gameBA = "Tham gia";
         COUNTINUE = "Tiếp tục";
         NEW_ACC_ARLET = "Tài khoản của bạn chưa được xác thực. Nếu bạn xóa trò chơi, hoặc đăng nhập tài khoản khác, nhân vật đang chơi của bạn sẽ mất vĩnh viễn.";
         NEW_PLAY = "Chơi mới";
         COUNTINUE_PLAY = "Chơi tiếp";
         CHANGE_ACC = "Đổi tài khoản";
         SERVER = "Máy Chủ: ";
         gameBB = "hạng";
         gameBC = "Thách Đấu";
         gameBD = "Thông tin";
         tips = new String[]{"Bạn có thể nhấn giữ nút chuyển mục tiêu để hiển thị danh sách người chơi khác trong map", "Đối với máy có bàn phím, bạn có thể gán phím tắt cho các phím 7,8,9 hoặc Q,W,E để sử dụng kỹ năng", "Cừu sát sẽ làm tăng 2 điểm hiếu chiến. Đồ sát sẽ làm tăng 1 điểm hiếu chiến", "Đối với Kiếm, Kunai, Đao: Nên tăng Sức Mạnh, Thể Lực, Thân pháp", "Đối với Cung, Phi Tiêu, Quạt: Nên tăng Chakra, Thể Lực, Thân pháp", "Lập tổ đội đi luyện cùng nhau bạn sẽ nhận được nhiều kinh nghiệm hơn và làm nhiệm vụ nhanh hơn", "Để giảm hiếu chiến, bạn phải bị người khác đánh trọng thương. Vào đấu trường để thi đấu để giảm", "Khi tách đá khỏi trang bị, bạn sẽ thu lại một nửa số đá ép vào lúc đầu", "Bạn có thể đổi Xu từ Yên, với điều kiện có đủ điểm hoạt động", "Bạn sẽ có phần thưởng nếu đạt thành tích cao nhất trong đấu trường mỗi ngày", "Để vào khu vực đấu trường, hãy tìm Rikudou đứng ở mỗi trường", "Bạn có thể tăng tỉ lệ thành công khi nâng cấp đồ bằng cách chọn phương pháp Cẩn Thận, nhưng sẽ tốn Lượng", "Bạn được tặng 10 lượng khi đạt cấp độ 20 tại NPC Okanechan", "Tiền Lượng được chia sẻ cho 3 nhân vật trong 1 tài khoản"};
         gameBE = "Quy định";
         gameBG = "Xin chờ..";
         gameBH = "Chờ";
         gameBI = "Menu";
         gameBJ = "Cần";
         gameBK = "Di chuyển tới";
         LANGUAGE = "Ngôn ngữ";
         gameBM = "Xóa bộ nhớ tạm";
         LANGUAGES = new String[]{"Tiếng việt", "English"};
         var10000 = new String[]{"ភាសាខ្មែរ", "ភាសាអង់គ្លេស"};
         gameBO = "Bạn có muốn thoát game để chọn lại ngôn ngữ không ?";
         CLOSE = "Đóng";
         gameBQ = "Ẩn";
         gameBR = "Tự đánh";
         gameBS = "Đứng yên";
         gameBT = "do";
         gameBU = "Khóa";
         gameBV = "Mở khóa";
         gameBW = "Số seri";
         gameBX = "Mã thẻ";
         gameBY = "Bật";
         gameBZ = "Tắt";
         gameCA = "Mở link";
         gameCB = "Nạp";
         gameCC = "Kích hoạt";
         gameCD = "Cấu hình";
         DELETE = "Xóa";
         gameCF = "Xem";
         gameCG = "Tiếp tục";
         gameCH = "Mã rương";
         gameCI = "Thẻ cào";
         gameCJ = "Tiếp";
         gameCK = "Sử dụng";
         gameCL = "Sắp xếp";
         gameCM = "Bỏ ra đất";
         gameCN = "Tách";
         gameCO = "Trang bị đã được tách, bạn nhận được ";
         YES = "Có";
         gameCQ = "Lấy ra";
         gameCR = "Bỏ ra";
         gameCS = "Rút xu";
         gameCT = "Cất xu";
         gameCU = "Chuyển xu";
         gameCV = "Cất vào";
         gameCW = "Bán";
         gameCX = "Bán nhiều";
         gameCY = "Bán hết";
         gameCZ = "Giá";
         gameDA = "Mua";
         gameDB = "Mua nhiều";
         NO = "Không";
         EXIT = "Thoát";
         CHAT = "Chat";
         OK = "OK";
         USERNAME = "Tài khoản";
         PASSWORD = "Mật khẩu";
         REPASS = "Nhập lại";
         gameDJ = "TK";
         gameDK = "MK";
         gameDL = "lại";
         RESTART = "Xin khởi động lại game.";
         REPASSWORD = "Nhập lại mật khẩu";
         REMEMBER = "Nhớ";
         UNCHECK = "Bỏ";
         gameDQ = "Đăng ký";
         gameDR = "Tăng đồ họa (cho máy mạnh)";
         gameDS = "Giảm đồ họa (cho máy yếu)";
         NOT_INPUT_USERNAME = "Bạn chưa nhập tên tài khoản";
         NOT_SPEC_CHARACTER = "Tài khoản không được có ký tự đặt biệt.";
         NOT_INPUT_PASS1 = "Bạn chưa nhập mật khẩu lần một.";
         NOT_INPUT_PASS2 = "Bạn chưa nhập mật khẩu lần hai.";
         USERNAME_LENGHT = "Tên tài khoản phải nhiều hơn 5 ký tự";
         WRONG_PASSWORD = "Mật khẩu không chính xác.";
         REGISTER_TEXT = new String[]{"Để xác thực với tên", "bạn phải đồng ý với quy định của trò chơi."};
         gameEA = "Bạn đang sử dụng mạng gì? (Bạn có thể chọn lại từ Menu)";
         ASK_REG_NUM = "Có phải bạn dùng số điện thoại đăng ký không ?";
         gameEC = "tin nhắn riêng";
         gameED = new String[]{"Tin nhắn gia tộc, nhóm", "Tin nhắn gia tộc", "Tin nhắn nhóm"};
         gameEE = "hộ tống";
         gameEF = "Cộng";
         gameEG = "Cộng nhiều";
         gameEH = "điểm tiềm năng";
         ACCEPT = "Đồng ý";
         CANCEL = "Hủy";
         gameEK = "Danh sách";
         gameEL = "Thời gian";
         gameEM = "Thành tích";
         gameEN = "Tối đa";
         gameEO = "Tích lũy";
         CONNECTING = "Đang kết nối";
         REGISTERING = "Đang đăng ký";
         LOGGING = "Đang đăng nhập";
         gameES = "Chưa hoàn thành";
         gameET = "Thời gian hoàn thành";
         gameEU = "Tinh thần đồng đội";
         SELECT = "Chọn";
         gameEW = "Bỏ chọn";
         gameEX = "Chọn vật phẩm để xem thông tin.";
         gameEY = "Gán";
         gameEZ = "Kết quả";
         gameFA = "Đánh giá";
         gameFB = "Cấp";
         gameFC = "cấp";
         gameFD = "Bạn có muốn thoát không?";
         gameFE = "Nhân vật cần đổi tên";
         gameFF = "Máy chủ này đang bảo trì hoặc quá tải. Vui lòng thử lại sau hoặc chọn máy chủ khác.";
         gameFG = "Tạo mới";
         CHARNAME = "Tên nhân vật";
         gameFI = "Tên nhân vật muốn kết bạn";
         gameFJ = "đã trở thành hảo hữu.";
         gameFK = "Đang tải... ";
         gameFL = "Đóng";
         gameFM = "Nhận thưởng";
         gameFN = "rương hang động";
         gameFO = "Hành trang đã được mở rộng";
         gameFP = "Khoảng cách hộ tống quá xa, nhiệm vụ đã thất bại";
         gameFQ = "Người được hộ tống đã trọng thương, nhiệm vụ đã thất bại";
         gameFR = "vĩnh viễn";
         gameFS = "Chưa nâng cấp";
         gameFT = "Không thể nâng cấp";
         gameFU = "Dùng vật phẩm đặc biệt để nâng cấp";
         gameFV = "Luyện";
         gameFW = "Luyện đá thành công, bạn nhận được";
         gameFX = new String[]{"Chỉ được chuyển hóa trang bị cùng", "loại và cùng cấp trở lên.", "Sẽ khóa trang bị sau khi chuyển hóa."};
         gameFY = "thất bại, bạn nhận được";
         gameFZ = "Đã gửi tin nhắn, xin chờ tin nhắn xác nhận.";
         gameGA = "Không thể gởi tin nhắn. Xin kiểm tra tiền và thử khởi động lại game.";
         gameGB = "Xu đang gửi";
         gameGC = "Bắt đầu";
         gameGD = "Chọn 2 viên đá trở lên";
         gameGE = "Chọn Trang Bị cần tách Đá";
         gameGF = "Chọn Vật Phẩm và Xu trao đổi";
         gameGG = "Sang Hành Trang để chọn";
         CHANGE = "Đổi";
         gameGI = "ô";
         gameGJ = "ô thứ";
         gameGK = new String[]{"Phím Q", "Phím W", "Phím E"};
         gameGL = new String[]{"Phím 7", "Phím 8", "Phím 9"};
         HAIR_STYLE = new String[][]{{"ngắn", "cài trâm", "búi", "xù"}, {"đeo băng", "bó xù", "samurai", "nhím"}};
         gameGN = new String[]{"Hành trang", "Kỹ năng", "Tiềm năng", "Thông tin", "Trang bị", "Thú Cưỡi"};
         gameGO = new String[]{"Tiệm Y Phục", "Hành trang"};
         gameGP = new String[]{"Nón", "Hành trang"};
         gameGQ = new String[]{"Áo", "Hành trang"};
         gameGR = new String[]{"Găng tay", "Hành trang"};
         gameGS = new String[]{"Quần", "Hành trang"};
         gameGT = new String[]{"Giày", "Hành trang"};
         gameGU = new String[]{"Dây chuyền", "Hành trang"};
         gameGV = new String[]{"Nhẫn", "Hành trang"};
         gameGW = new String[]{"Ngọc bội", "Hành trang"};
         gameGX = new String[]{"Bùa", "Hành trang"};
         gameGY = new String[]{"Binh khí", "Hành trang"};
         gameGZ = new String[]{"Dược phẩm", "Hành trang"};
         gameHA = new String[]{"Dược phẩm", "Hành trang"};
         gameHB = new String[]{"Thức ăn", "Hành trang"};
         gameHC = new String[]{"Thức ăn", "Hành trang"};
         gameHD = new String[]{"Nâng cấp", "Hành trang"};
         gameHE = new String[]{"Gian hàng", "Hành trang"};
         gameHF = new String[]{"Chuyển hóa", "Hành trang"};
         gameHG = new String[]{"Luyện đá", "Hành trang"};
         gameHH = new String[]{"Rương đồ", "Hành trang"};
         gameHI = new String[]{"Cửa hàng", "Quầy sách", "Thời trang", "Gia Tộc"};
         gameHJ = new String[]{"Bảo vật"};
         gameHK = new String[]{"Tách Đá", "Hành trang"};
         gameHL = new String[]{"Giao dịch", "Hành trang"};
         gameHM = new String[]{"Luyện thạch", "Hành trang"};
         gameHN = new String[]{"Dịch chuyển", "Hành trang"};
         gameHO = new String[]{"Tinh luyện", "Hành trang"};
         gameHP = new String[]{"Khảm ngọc", "Hành trang"};
         gameHQ = new String[]{"Luyện ngọc", "Hành trang"};
         gameHS = new String[]{"Gọt ngọc", "Hành trang"};
         gameHR = new String[]{"Giao đồ", "Hành trang"};
         gameHT = new String[]{"Tháo ngọc", "Hành trang"};
         gameXN = new String[]{"Nhặt đồ", "Hành trang"};
         var10000 = new String[]{"Del đồ", "Hành trang"};
         gameXO = "Xóa";
         gameXP = "Thêm";
         gameAU = "Ta sẽ làm giảm đi chỉ số bất lợi trên viên ngọc này.";
         gameAV = "Ta sẽ giúp ngươi tháo bỏ ngọc khảm trên trang bị.";
         gameHU = new String[]{"- Sử dụng Yên, nếu không đủ dùng Xu", "- Qua trang Hành Trang để chọn Đá", "- Số lượng đá từ 2 đến 24"};
         gameHV = new String[]{"- Sử dụng Yên, nếu không đủ dùng Xu", "- Nâng cấp cẩn thận cần dùng lượng", "- Chỉ chọn Trang Bị và Đá", "Trang bị đã được nâng cấp tối đa"};
         gameHW = new String[]{"- Sử dụng Yên, nếu không đủ dùng Xu", "- Chỉ chọn Trang Bị và Ngọc"};
         gameHX = "Khóa G.Dịch";
         gameHY = "- Luyện thành Đá cấp";
         gameHZ = "- Cần: # yên";
         gameKA = "- Cần: # lượng";
         gameKB = "- Cần: # xu";
         gameKC = "- Xác xuất thành công";
         gameKD = "(thành công ";
         gameKE = "Cộng";
         gameKG = "Đã khóa";
         gameKH = "Tiêu diệt";
         gameKI = "Bắt tà thú";
         gameKJ = "Tiêu diệt tinh anh";
         gameKK = "Tiêu diệt thủ lĩnh";
         gameKL = "Hộ tống trẻ lạc";
         gameKM = "Không khóa";
         gameKN = "Hạn sử dụng";
         gameKO = "Giá bán: # yên";
         gameKP = "Giá mua: # xu";
         gameKQ = "Giá mua: # xu gia tộc";
         gameKR = "Giá mua: # yên";
         gameKS = "Giá mua: # lượng";
         gameKT = "lượng";
         gameKU = "Chưa có";
         gameKV = "Cấp kế: cấp #";
         gameKW = "Cấp hiện tại: cấp #";
         gameKX = "Cấp tối đa";
         gameKY = "Đã đạt cấp độ tối đa";
         gameKZ = "Yêu cầu: trình độ cấp";
         gameMA = "Lớp: ";
         gameMB = new String[]{"Chính tuyến", "Phụ tuyến"};
         ME_TASK = "Nhiệm vụ";
         gameMD = "Nhận NV ở";
         gameME = "Bạch giả";
         gameMF = "Hắc giả";
         gameMG = "Trung lập";
         gameMH = "Nhóm";
         gameMI = "Tìm Nhóm";
         gameMJ = "Điểm hiếu chiến của bạn hiện tại là ";
         gameMK = new String[]{"Bạn bè", "Thù Địch"};
         gameML = "Bạn chưa kết bạn với ai";
         gameMM = "chờ xác nhận";
         gameMN = "đã thêm bạn vào danh sách bạn bè";
         gameMO = "Bạn đã thêm";
         gameMP = "vào danh sách";
         gameMQ = "Bạn và";
         gameMR = new String[]{"Cửa hàng", "Bản thân", "Bản đồ", "Tổng hợp", "Thoát", "Trang sức", "Tính năng", "Dược khóa", "Dược phẩm", "Tạp hóa khóa", "Tạp hóa", "Cường hóa", "Luyện hóa", "Luyện hóa khóa", "Thủ khố", "Tách trang bị", "Khu vực", "Giao dịch", "Tin nhắn", "Chọn Nhân vật"};
         gameMS = new String[]{"Hỗ trợ bị động", "Chủ động sử dụng", "Chủ động sử dụng", "Chủ động sử dụng", "Chủ động sử dụng"};
         gameMT = new String[]{"Nhân vật: ", "Hiếu chiến: ", "Trình độ: ", "Lớp: ", "", "HP: ", "MP: ", "Tốc độ: ", "Tấn công: ", "Hỏa chống: ", "Băng chống: ", "Phong chống: ", "Giảm sát thương: ", "Độ chính xác: ", "Khả năng né đòn: ", "Chí mạng: ", "Phản đòn cận chiến: ", "Cường khắc: ", "Hạ khắc: ", "Điểm hoạt động: "};
         gameMU = " lần";
         gameMV = new String[]{"Học Giả", "Hạ nhẫn", "Trung Nhẫn", "Thượng Nhẫn", "Nhẫn Giả"};
         gameMW = new String[]{"Điểm hoạt động: ", "Danh vọng vũ khí: ", "Danh vọng dây chuyền: ", "Danh vọng nhẫn: ", "Danh vọng ngọc bội: ", "Danh vọng bùa: ", "Danh vọng nón: ", "Danh vọng áo: ", "Danh vọng găng tay: ", "Danh vọng quần: ", "Danh vọng giày: ", "Hoàn thành NV mỗi ngày: ", "Truy bắt Tà Thú còn: ", "Học sách tiềm năng sơ: ", "Học sách kỹ năng sơ: ", "Gia tộc: ", "Vào hang động còn: ", "Điểm tinh tú: ", "Số lần ăn bánh phong lôi: ", "Số lần ăn bánh băng hỏa: "};
         gameMX = new String[]{"Tên: ", "Giới tính: ", "Tóc: "};
         MENUGENDER = new String[]{"Nữ", "Nam"};
         gameMZ = new String[]{"Sức mạnh", "Thân pháp", "Thể lực", "Chakra"};
         gameNA = "Chưa có ai cừu sát bạn";
         gameNB = "Bạn đã thắng #.";
         gameNC = "Bạn đã thua #.";
         gameND = "Cuộc so tài giữa bạn và # đã kết thúc";
         gameNE = new String[]{"", "Tinh Anh", "Thủ Lĩnh", "Tà Thú"};
         gameNF = " bắt đầu cừu sát bạn";
         gameNG = "Điểm tiềm năng";
         gameNH = "Điểm kỹ năng";
         gameNI = "Không đủ MP để sử dụng";
         gameNJ = "Chỉ được vật phẩm không khóa";
         gameNK = "Chỉ được chọn vật phẩm không khóa và không có hạn sử dụng";
         gameNL = "Chỉ được chọn Đá để luyện cấp";
         gameNM = "Chỉ được chọn Đá, Trang bị, và Bảo hiểm để nâng cấp";
         gameNN = "Chỉ được chọn Trang bị và vật phẩm Hoán chuyển.";
         gameNO = "Trang bị không thể nâng cấp";
         gameNP = "Trang bị đã nâng cấp tối đa";
         gameNQ = "Chỉ được chọn trang bị đã nâng cấp mới có thể tách được";
         gameNR = "Vật phẩm giao dịch đã đầy";
         gameNS = "Số lượng đã đầy";
         gameNT = "Bạn không đủ điểm cộng";
         gameNU = "Bạn chưa nhập điểm cộng";
         gameNV = "Bạn chưa nhập thông tin loại thẻ";
         gameNW = "Bạn chưa nhập thông tin mệnh giá.";
         gameNX = "Bạn chưa nhập thông tin số seri";
         gameNY = "Bạn chưa nhập thông tin khoảng thời gian nạp.";
         gameNZ = "Bạn chưa nhập vào tên cần thêm";
         gamePA = "Nhập điểm";
         gamePB = "Nhập Xu";
         gamePC = "Nhập số lượng";
         INPUT_NICK = "Tên tài khoản";
         gamePE = "Xu";
         gamePF = "Yên";
         gamePG = "Lượng";
         gamePH = "Cất vào hành trang";
         gamePI = "Bạn có thật sự muốn bãi nhiệm chức vụ của người này không?";
         gamePJ = "Trục xuất thành viên sẽ bị giảm ngân sách gia tộc (xem chi tiết tại Npc Kanata). Bạn có thật sự muốn trục xuất người này không?";
         gamePK = "Tự rời khỏi gia tộc sẽ bị giảm xu trong hành trang (xem chi tiết tại Npc Kanata). Bạn có muốn rời khỏi không?";
         gamePL = "Sau khi sử dụng vật phẩm sẽ bị khóa. Bạn có muốn sử dụng không?";
         gamePM = "Sau khi bán vật phẩm sẽ không thể phục hồi. Bạn có muốn bán vật phẩm này không?";
         gamePN = new String[][]{{"nón"}, {"vũ", "khí"}, {"áo"}, {"vòng", "cổ"}, {"găng", "tay"}, {"nhẫn"}, {"quần"}, {"bội"}, {"giày"}, {"bùa"}, {"thú", "nuôi"}, {"mặt", "nạ"}, {"ninja", "yoroi"}, {"gia", "tộc"}, {"chưa", "mở"}, {"bí", "kíp"}, {"áo", "giáp"}, {"yên", ""}, {"cương", ""}, {"trang", "sức"}, {"động", "cơ"}, {"định", "vị"}, {"bộ", "đk"}, {"bình", "nitro"}};
         gamePO = new String[]{"Chưa vào trường", "Trường: Hirosaki", "Trường: Ookaza", "Trường: Haruna"};
         gamePP = new String[]{"", "Thuộc tính: Hỏa", "Thuộc tính: Thủy", "Thuộc tính: Phong", "", "", ""};
         gamePQ = "Bạn nhận được";
         gamePR = "Bạn chưa nhập vào số lương";
         gamePS = "Không thể bán trang bị đã nâng cấp";
         gamePT = "Bạn không đủ xu để chuyển.";
         gamePU = "Bạn không đủ xu để cất";
         gamePV = "Bạn không đủ xu để rút";
         gamePW = "Bạn không đủ số lượng để bán";
         gamePX = new String[]{"Thành công, trang bị được lên cấp ", "Thất bại, trang bị trở về cấp ", "Trang bị được nâng cấp tối đa", "Trang bị cấp"};
         gamePY = new String[]{"Khảm ngọc thành công", "Khảm ngọc thất bại"};
         MONTH = "tháng";
         WEEK = "tuần";
         DAY = "ngày";
         HOUR = "giờ";
         gameQD = "giây";
         MINUTE = "phút";
         gameQF = "Ảnh hưởng";
         gameQG = "Phạm vi";
         gameQH = "MP mất";
         gameQI = "Khoảng cách thi triển";
         gameQJ = "Phải có từ 2 viên đá trở lên mới có thể luyện được";
         gameQK = "Giới tính không phù hợp";
         gameQL = "Không có người chơi khác";
         gameQM = "Trình độ của bạn chưa đạt yêu cầu";
         gameQN = "Đá đã đạt cấp độ tối đa";
         gameQO = "Đá sau khi luyện cấp sẽ bị khóa. Bạn có muốn tiếp tục không?";
         gameQP = "Bạn không đủ xu để luyện đá";
         gameQQ = "Bạn không đủ lượng để nâng cấp trang bị";
         gameQR = "Bạn không đủ xu hoặc yên để nâng cấp trang bị";
         gameQS = "Nhiều đá quá sẽ bị lãng phí. Bạn có chắc chắn muốn nâng cấp?";
         gameQT = "Sau khi nâng cấp trang bị sẽ bị khóa. Bạn có muốn tiếp tục không?";
         gameQU = "Không thể tách trang bị chưa nâng cấp";
         gameQV = "Hành trang không đủ chỗ trống";
         gameQW = "Bạn có thật sự muốn tách không?";
         gameQX = "Bạn có thật sự muốn chuyển hóa không?";
         gameQY = "mời bạn giao dịch. Bạn có muốn giao dịch không?";
         gameQZ = "mời bạn vào tộc. Bạn có muốn là thành viên của gia tộc '#' không?";
         gameRA = "muốn xin vào gia tộc. Bạn có đồng ý không?";
         gameRB = "muốn tỷ thí với bạn. Bạn có đồng ý không?";
         gameRD = "mời bạn vào nhóm. Bạn có muốn vào không?";
         gameRE = "muốn xin vào nhóm. Bạn có đồng ý không?";
         gameRF = "Chuyển hóa trang bị thành công.";
         gameRG = new String[]{"Giới tính: nữ", "Giới tính: nam"};
         gameRH = "Khu vực";
         gameRI = "Dân số";
         gameRJ = "Nhóm";
         gameRK = "Hiện tại bạn không vào nhóm nào";
         gameRL = "lần";
         gameRM = new String[]{"Thông tin", "Thành viên", "Nhà Kho", "Thống Kê", "Thần Thú"};
         gameRN = new String[]{"Gia tộc: ", "Tộc trưởng: ", "Thành viên: ", "Cấp: ", "Kinh nghiệm: ", "Ngân sách: ", "Thành lập: ", "Cống hiến: ", "Phí duy trì: ", "Phí nâng cấp: ", "Vào Lãnh Địa Gia Tộc: còn ", "Cống hiến tuần: ", "Sử dụng lệnh bài còn: "};
         CLAN_ACTIVITY = new String[]{"xu lúc", "Thành lập gia tộc, ngân sách nhận", "bị trục xuất, ngân sách trừ", "đóng góp quỹ gia tộc, ngân sách tăng", "rút quỹ gia tộc, ngân sách giảm", "Thu phí duy trì gia tộc, ngân sách giảm", "nâng cấp gia tộc, ngân sách giảm"};
         gameRP = "Hiện tại bạn chưa gia nhập gia tộc";
         gameRQ = "Phát cho Thành viên";
         gameRR = new String[][]{{"Trường Hirosaki"}, {"Trường Haruna"}, {"Trường Ookaza"}, {"Làng", "Làng Kojin", "Làng Sanzu", "Làng Tone", "Làng chài", "Làng Chakumi", "Làng Echigo", "Làng Oshin"}, {"Khu vực"}};
         gameRS = new String[]{"Nón", "Nhân", "Áo", "Dây chuyền", "Găng tay", "Nhẫn", "Quần", "Ngọc bội", "Giày", "Bùa"};
         gameRT = new String[]{"Kích ẩn", "Kích cấp độ"};
         gameRU = new String[]{"", "Hỏa", "Thủy", "Phong"};
         CHARINGFO = new String[]{"Nhân vật", "Level", ""};
         gameRW = "Vô chiêu thắng hữu chiêu. Hiện tại bạn chưa có chiêu để đánh.";
         gameRX = "Bạn chưa có vũ khí. Xin vào Menu/Bản Thân/Trang bị để kiểm tra";
         gameRY = "Vật phẩm đã bị khóa";
         gameRZ = "Vật phẩm, trang bị và đá";
         gameSA = "Mức giá (xu)";
         gameSB = "Mức giá (yên)";
         gameSC = "Đã hết hiệu quả thức ăn";
         gameSD = "Level của bạn không đủ để sử dụng";
         gameSE = "Đã hết bình MP";
         gameSF = "Đã hết bình HP";
         gameSG = new String[]{"Giao dịch", "Tỷ thí", "Cừu sát", "Kết bạn", "Mời vào nhóm", "Phục hồi", "Xem thông tin", "Chat riêng", "Mời vào tộc", "Xin vào tộc", "Chặn xin vào tộc", "Tự Hồi Sinh", "Cấm Chat"};
         gameSH = "Bạn đang ở khu vực này";
         gameSI = new String[]{"Hãy đi tìm ", " ở ", " để nhận nhiệm vụ.", "Bạn đã hoàn thành hết nhiệm vụ phiên bản này, vui lòng chờ cho đến khi ra phiên bản tiếp theo."};
         gameSJ = new String[]{"Kiệt sức", "Đứng nhìn", "Quay về", "Hồi sinh tại chỗ (1 lượng)"};
         gameSK = "Sau khi gia nhập vào lớp học, thì có thể nhận nhiệm vụ từ hiệu trưởng";
         gameSL = "Tạo nhóm";
         gameSM = "Rời nhóm";
         gameSN = "Nhóm trưởng";
         gameSO = "Khóa nhóm";
         gameSP = "Mở nhóm";
         gameSQ = "Xin gia nhập";
         gameSR = "Tìm lại";
         gameSS = "Hiện tại bạn chưa có nhóm";
         gameST = "Chưa có thông tin";
         gameSU = "Hiện tại không tìm thấy nhóm";
         gameSV = new String[]{"PK Thường", "PK Phe", "PK Bang", "PK Đồ Sát"};
         gameSW = new String[]{"Trạng thái PK", "Bạn bè", "Thù Địch", "Nhóm", "Tìm nhóm", "Gia tộc", "Bảo vệ tài khoản", "Tự động", "Bán Shinwa", "Luyện thạch", "Tinh luyện", "Dịch chuyển"};
         gameSX = new String[]{"Bản đồ", "Nhiệm vụ", "Gia tộc"};
         gameSY = new String[]{"Tộc trưởng", "Tộc phó", "Trưởng lão", "Ưu tú", "Thành viên"};
         gameSZ = new String[]{"(TT)", "(TP)", "(TL)", "(UT)"};
         gameTA = new String[]{"Chỉ hiện Online", "Rời khỏi", "Thông báo", "Đóng góp", "Rút quỹ", "Nâng Cấp", "Mời vào lãnh địa", "Mời vào Gia tộc chiến", "Khai mở"};
         gameTB = "SX theo C.Hiến tuần";
         gameTC = new String[]{"Trục xuất", "Nhường", "Kết bạn"};
         gameTD = " được lên làm nhóm trưởng.";
         gameTE = "Bạn bị đuổi ra khỏi nhóm";
         gameTF = "Mời vào nhóm";
         gameTG = "Thêm";
         gameTH = "Vũ khí không thích hợp.";
         gameTI = "Bạn có muốn xóa người này ra khỏi danh sách?";
         gameTJ = new String[]{"Bạn phải vào trường để tăng điểm"};
         gameTK = new String[]{"Sức mạnh = Tấn công", "Thân pháp = né,chính xác", "Thể lực = HP", "Chakra = MP"};
         gameTL = new String[]{"Không cần tăng sức mạnh", "Thân pháp = né,chính xác", "Thể lực = HP", "Chakra = Tấn công, MP"};
         CLOSE_CURTAB = "Đóng tab hiện tại";
         PUBLICCHAT = new String[]{"Công cộng", "Bạn có thể chat với người đứng gần tại đây"};
         PARTYCHAT = new String[]{"Chung nhóm", "Bạn có thể chat với người trong cùng nhóm tại đây"};
         GLOBALCHAT = new String[]{"Kênh thế giới", "Bạn mất 5 lượng mỗi lần chat kênh thế giới.", "Tất cả người đang online đều thấy bạn chat.", "Bạn sẽ bị khóa tài khoản nếu chửi bậy, quảng cáo wap web trên kênh thế giới."};
         CLANCHAT = new String[]{"Gia tộc", "Bạn có thể chat với người trong gia tộc tại đây"};
         gameTR = "Chặn kênh thế giới: ";
         gameTS = "Chặn chat riêng: ";
         gameTT = "Bổ nhiệm";
         gameTU = "Bãi nhiệm";
         gameTV = "Trục xuất";
         gameTW = "Mật khẩu phải có độ dài là 6 ký tự.";
         gameTX = "Mật khẩu bảo vệ chỉ cho nhập số.";
         gameTY = "Mật khẩu bảo vệ không được chứa số 0 ở đầu.";
         gameTZ = "Mật khẩu bảo vệ chưa đúng.";
         gameUA = "Để sử dụng chức năng này bạn phải có Vạn biến lệnh.";
         gameUB = "Kích hoạt chức năng này phải tốn 10.000 yên. Bạn có muốn kích hoạt không ?";
         gameUC = "Nhập mật khẩu bảo vệ";
         gameUD = "Nhập số điện thoại đăng ký";
         gameUE = "Bạn chưa nhập số điện thoại đăng ký.";
         gameUF = "Để lấy mật khẩu cho '#'. Bạn phải sử dụng số điện thoại đăng ký cho tài khoản này.";
         gameUG = "Đổi mật khẩu";
         gameUH = "Huỷ bảo vệ";
         gameUI = "Mật khẩu cũ";
         gameUJ = "Mật khẩu mới";
         gameUK = "Bạn học được ";
         gameUL = "Nhập thông báo";
         gameUM = "Nhập số xu cần rút";
         gameUN = "Nhập số xu đóng góp cho gia tộc";
         gameUO = "Nhập thông tin loại thẻ và mệnh giá";
         gameUP = "Nhập thông tin số seri và khoảng thời gian nạp";
         gameUQ = "Nhập số lượng tách";
         gameUR = "Mệnh giá";
         gameUS = "Loại thẻ";
         gameUT = "Số seri";
         gameUU = "Thời gian nạp";
         gameUV = "Chặn tin nhắn";
         gameUW = "Báo lỗi với Admin";
         gameUX = new String[]{"Gán phím tắt", "Gán vào 5 ô đánh"};
         gameUY = "Gửi tin nhắn thành công";
         gameUZ = "Chúc mừng bạn đã gởi tin nhắn dự đoán thành công.";
         gameVA = "Không thể gửi tin nhắn";
         gameVB = "Tin nhắn gửi không thành công.";
         gameVC = "Không đủ xu để đóng góp";
         gameVD = "Số lượng tách không hợp lệ.";
         gameVE = "Giá trị nhập không hợp lệ.";
         gameVF = "Bạn có muốn hủy chức năng bảo vệ tài khoản không ?";
         gameRC = "muốn thách đấu với bạn ở lôi đài. Bạn có đồng ý không?";
         gameVG = "Sắp xếp theo giá";
         gameVH = "Sắp xếp theo cấp";
         gameVI = "Sắp xếp theo tên";
         gameVJ = "Vật phẩm đã được gởi bán vào gian hàng";
         gameVK = "Mức phí cho mỗi lần bán là 5.000 xu";
         gameVM = "Bạn có muốn bán vật phẩm với giá # xu không ?";
         gameVN = "Bạn có muốn mua vật phẩm với giá # xu không ?";
         gameVO = "Người bán";
         gameVP = "còn";
         gameVQ = "gần";
         gameVR = "hết giờ";
         gameVS = new String[]{"Đá", "Nón", "Vũ khí", "Áo", "Dây chuyền", "Găng tay", "Nhẫn", "Quần", "Ngọc bội", "Giày", "Bùa", "Linh tinh"};
         gameVL = " Vật phẩm bán được chịu thuế là 1%";
         gameKF = "Kinh nghiệm";
         gameVT = "Thông báo Server";
         gameVU = "Giới thiệu bạn bè";
         gameVV = "Lật hình";
         gameVW = "Số lượt lật còn lại của bạn là: ";
         gameVX = "muốn thách đấu với bạn và cả gia tộc. Bạn có đồng ý không?";
         gameVY = "Max options";
         gameVZ = "Mời người này";
         gameWA = "Mời tất cả";
         gameWB = "'#' mời bạn vào gia tộc chiến. Bạn có muốn vào không?";
         gameWC = "Nhập tên thành viên";
         gameWD = new String[][]{{"Yêu cầu: gia tộc đạt cấp 5.", "Phí khai mở: 1.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 10.", "Phí khai mở: 5.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 15.", "Phí khai mở: 10.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 20.", "Phí khai mở: 20.000.000 xu gia tộc."}, {"Yêu cầu: gia tộc đạt cấp 25.", "Phí khai mở: 30.000.000 xu gia tộc."}};
         gameWE = new String[]{"Dùng HP khi còn dưới: ", "Dùng MP khi còn dưới:", "Dùng thức ăn cấp: ", "Dùng chiêu hổ trợ", "Dùng khiên mana", "Dùng đốt quái & ẩn thân", "Dùng phân thân", "Nhặt yên", "Nhặt HP, MP", "Nhặt N.Liệu(Đá)", "Luyện đá Max", "Nhặt Trang Bị", "Nhặt Trang Bị Lạ", "Nhặt VP Nhiệm Vụ", "Nhặt VP Sự Kiện", "Nhặt All", "Nhặt SVC", "Không nhặt gì cả", "Auto TTT", "AutoTTC", "ReMap", "Tàn sát map trống", "Auto Mua Thức Ăn", "TS khi hết MP", "Auto Reconnect", "Chuyển Map Hết Boss", "Săn TATL", "Đánh Quái Thường", "Đánh Tinh Anh", "Đánh Thủ Lĩnh", "Cộng tiềm năng", "Cộng kĩ năng", "Đánh theo nhóm", "Né PK","Dùng Cổ Lệnh","Mua Cổ Lệnh"};
         gameWF = "Dùng phím < và > để đổi giá trị";
         gameWG = "Chạm vào ô thông số để đổi giá trị";
         gameWH = "Khoảng cách quá xa, không thể phục hồi cho người khác được";
         gameWI = "     Nhập giá trị phần trăm thấp tối thiểu            (Từ 10 đến 90)";
         gameWJ = new String[]{"Cấp 1", "Cấp 10", "Cấp 20", "Cấp 30", "Cấp 40", "Cấp 50", "Cấp 60", "Cấp 70"};
         gameWK = new String[]{"Cấp 1", "Cấp 2", "Cấp 3", "Cấp 4", "Cấp 5", "Cấp 6", "Cấp 7", "Cấp 8", "Cấp 9", "Cấp 10", "Cấp 11", "Cấp 12"};
         gameWL = "Tài khoản đang được bảo vệ, vui lòng mở khóa.";
         gameWM = "Sinh lực";
         gameWN = "Tên thú cưỡi";
         gameWO = new String[]{"Luyện thạch cấp cao hơn bằng cách", "dùng 9 thạch cùng loại hoặc 3 thạch sơ", "và đá 11 hoặc 3 thạch trung và đá 12."};
         gameWP = "Chỉ được chọn Tử tinh thạch sơ và trung cấp";
         gameWQ = "Chỉ được chọn Đá và Tử tinh thạch để luyện";
         gameWR = "Chỉ cần dùng 1 viên đá để luyện";
         gameWS = "Cần kết hợp 3 Tử tinh thạch (trung) và đá 12 hoặc 3 tử tinh thạch (sơ) đá 11";
         gameWT = "Chỉ được chọn đá cấp 11 trở lên";
         gameWU = "Chỉ được chọn Tử thiên thạch cùng loại";
         gameWV = "Phải có từ 3 Tử tinh thạch trở lên mới có thể luyện được";
         gameWW = "Số lượng Tử tinh thạch quá nhiều";
         gameWX = "Vật phẩm này không thể tinh luyện";
         gameWY = "Cần phải có đủ 20 chuyển tinh thạch để dịch chuyển trang bi";
         gameWZ = "Vật phẩm này không dùng trong dịch chuyển";
         gameXA = "Cất kẹo";
         gameXB = "Độ tinh luyện";
         gameXC = "Động cơ";
         gameXD = "Nhiên liệu";
         gameXE = "Cho kẹo";
         gameXF = new String[]{"tử tinh", "tử tinh thạch sơ", "tử tinh thạch trung", "tử tinh thạch cao"};
         gameXG = "Vật phẩm đã tinh luyện đến mức tối đa";
      } else {
         if (languageID == 1) {
            gameAJ = "This gem can't roasting.";
            gameAI = "This gem reached max level.";
            gameAK = "Register account to keep your character safe. Do you want to register?";
            gameAL = "Hidden quest";
            gameAM = "- Get 1 aggressive point.";
            gameAN = "- Complete the cave of near school yard 1 times.";
            gameAO = "- Complete hunting wild beast 1 times.";
            gameAP = "- Upgrade equipment successful 1 times.";
            gameAQ = "- Complete daily quest 10 times.";
            gameAR = "- Get 1000 battlefield points.";
            gameAS = "- Complete seven beasts gate 1 times.";
            gameAT = "- Enjoy lucky card 3 times.";
            var10000 = new String[]{"Katana", "Bokken", "Shuriken", "Tessen", "Kunai", "General Server"};
            gameAW = "Win rate";
            gameAX = "Your coin: ";
            gameAY = "Players: ";
            gameAZ = "Lucky draw";
            gameBA = "Join now";
            COUNTINUE = "Continue";
            NEW_ACC_ARLET = "Your account has not been verified. If you delete the game, or log another account, your character will lose playing forever.";
            NEW_PLAY = "New Play";
            COUNTINUE_PLAY = "Play";
            CHANGE_ACC = "Change Username";
            SERVER = "Server: ";
            gameBB = "rank";
            gameBC = "Challenge";
            gameBD = "Info";
            tips = new String[]{"Press change focus button to show all players on map", "For keyboard phones, assign shortcut keys 7,8,9 (or Q,W,E) to use skills.", "Berserk mode adds +2 agressive points.  Kill adds +1 agressive", "Sword, Kunai,and Blade increases Strength, Constitution, Dexterity", "Bow, Shuriken and Fan increases Chakra, Constitution, Dexterity", "Training as a team will earn experience and complete tasks faster", "Fighing other players on the battlefield will decrease combative points.", "When separated from the stone equipped, you will collect half amount of stone at the beginning.", "If you have enough action points, you can exchange coins from kin.", "The highest daily achievement in the arena will earn a reward.", "Find Rikudou to get into the arena.", "Precautionary measures cost money but will Increase the success rate of upgrading items", "When you reach Level 20, find Okanechan to received 10 gold bars.", "Gold bars will be split to 3 characters in 1 account"};
            gameBE = "Term";
            gameBG = "Xin chờ..";
            gameBH = "Wait";
            gameBI = "Menu";
            gameBJ = "Need";
            gameBK = "Move to";
            LANGUAGE = "Language";
            gameBM = "Clear cache";
            LANGUAGES = new String[]{"Tiếng việt", "English"};
            var10000 = new String[]{"ភាសាខ្មែរ", "ភាសាអង់គ្លេស"};
            gameBO = "Exit game to change the language ?";
            CLOSE = "Close";
            gameBQ = "Hide";
            gameBR = "Auto";
            gameBS = "Stand";
            gameBT = "by";
            gameBU = "Lock";
            gameBV = "Unlock";
            gameBW = "Seri number";
            gameBX = "Card code";
            gameBY = "On";
            gameBZ = "Off";
            gameCA = "Open link";
            gameCB = "Charge";
            gameCC = "Active";
            gameCD = "Config";
            DELETE = "Delete";
            gameCF = "View";
            gameCG = "Continue";
            gameCH = "Inventory code";
            gameCI = "Scratch card";
            gameCJ = "Next";
            gameCK = "Use";
            gameCL = "Sort";
            gameCM = "Throw it away";
            gameCN = "Split";
            gameCO = "Equipment has been split, you get ";
            YES = "Yes";
            gameCQ = "Get out";
            gameCR = "Get out";
            gameCS = "Withdraw coins";
            gameCT = "Store coins";
            gameCU = "Transfer coins";
            gameCV = "Store";
            gameCW = "Sell";
            gameCX = "Sell more";
            gameCY = "Sell all";
            gameCZ = "Price";
            gameDA = "Buy";
            gameDB = "Buy more";
            NO = "No";
            EXIT = "Exit";
            CHAT = "Chat";
            OK = "OK";
            USERNAME = "Account";
            PASSWORD = "Password";
            REPASS = "Re-input";
            gameDJ = "Account";
            gameDK = "Pass";
            gameDL = "re";
            RESTART = "Please restart game";
            REPASSWORD = "Re-input password";
            REMEMBER = "Remember";
            UNCHECK = "Uncheck";
            gameDQ = "Register";
            gameDR = "High Graphic";
            gameDS = "Low Graphic";
            NOT_INPUT_USERNAME = "Please input account name";
            NOT_SPEC_CHARACTER = "Account does not allow special characters.";
            NOT_INPUT_PASS1 = "You haven't added a password.";
            NOT_INPUT_PASS2 = "Your passwords do not match.";
            USERNAME_LENGHT = "Account name must have at least five characters";
            WRONG_PASSWORD = "Wrong password.";
            REGISTER_TEXT = new String[]{"To register with name", "you have to follow the game rule."};
            gameEA = "What operator are you using? (You can recheck it in Menu)";
            ASK_REG_NUM = "Are you using your phone number to create account ?";
            gameEC = "private message";
            gameED = new String[]{"message clan, group", "clan messages", "group message"};
            gameEE = "escort";
            gameEF = "Plus";
            gameEG = "Plus more";
            gameEH = "potential point";
            ACCEPT = "Accept";
            CANCEL = "Cancel";
            gameEK = "List";
            gameEL = "Time";
            gameEM = "Achievement";
            gameEN = "Max";
            gameEO = "Accumulate";
            CONNECTING = "Connecting";
            REGISTERING = "Registering";
            LOGGING = "Logging";
            gameES = "Not finished";
            gameET = "Time to finish";
            gameEU = "Teamwork";
            SELECT = "Select";
            gameEW = "Uncheck";
            gameEX = "Select items to view the information.";
            gameEY = "Assign";
            gameEZ = "Result";
            gameFA = "Review";
            gameFB = "Level";
            gameFC = "Level";
            gameFD = "Do you want to exit?";
            gameFE = "Please rename your character";
            gameFF = "This server is maintained or overloaded. Please try again later or choose another server.";
            gameFG = "Create";
            CHARNAME = "Name";
            gameFI = "Name of character you want to friend";
            gameFJ = "Friend link successful.";
            gameFK = "Loading... ";
            gameFL = "Close";
            gameFM = "Get reward";
            gameFN = "lucky gift";
            gameFO = "Inventory was expanded";
            gameFP = "Distance too far for escort, quest failed";
            gameFQ = "The escort was wounded, quest failed";
            gameFR = "forever";
            gameFS = "Not upgrade";
            gameFT = "Can not upgrade.";
            gameFU = "Use special items to upgrade";
            gameFV = "Train";
            gameFW = "Stone train successful, you get";
            gameFX = new String[]{"Just transfer same type equipment", " or higher.", "Will lock fitted after transformation.."};
            gameFY = "failure, you get";
            gameFZ = "Message sent, please wait for confirmation.";
            gameGA = "Can not send message. Please check you balance or restart the game.";
            gameGB = "Sending Coins";
            gameGC = "Start";
            gameGD = "Choose at least 2 stones or more";
            gameGE = "Choose the equipment that you want to split the Stone";
            gameGF = "Choose item and coins to exchange";
            gameGG = "Move to luggage to choose";
            CHANGE = "Change";
            gameGI = "Cell";
            gameGJ = "Cells";
            gameGK = new String[]{"Key Q", "Key W", "Key E"};
            gameGL = new String[]{"Key 7", "Key 8", "Key 9"};
            HAIR_STYLE = new String[][]{{"tomboy", "with brooch", "pony tail", "curly"}, {"head band", "afro", "samurai", "spike"}};
            gameGN = new String[]{"Inventory", "Skill", "Potential", "Info", "Equipment", "Mounts"};
            gameGO = new String[]{"Costume shop", "Inventory"};
            gameGP = new String[]{"Cap", "Inventory"};
            gameGQ = new String[]{"Cloth", "Inventory"};
            gameGR = new String[]{"Gloves", "Inventory"};
            gameGS = new String[]{"Pants", "Inventory"};
            gameGT = new String[]{"Shoes", "Inventory"};
            gameGU = new String[]{"Necklace", "Inventory"};
            gameGV = new String[]{"Ring", "Inventory"};
            gameGW = new String[]{"Gems", "Inventory"};
            gameGX = new String[]{"Charms", "Inventory"};
            gameGY = new String[]{"Weapons", "Inventory"};
            gameGZ = new String[]{"Medicine", "Inventory"};
            gameHA = new String[]{"Medicine", "Inventory"};
            gameHB = new String[]{"Food", "Inventory"};
            gameHC = new String[]{"Food", "Inventory"};
            gameHD = new String[]{"Upgrade", "Inventory"};
            gameHE = new String[]{"Stand", "Inventory"};
            gameHF = new String[]{"Transfer", "Inventory"};
            gameHG = new String[]{"Training Stone", "Inventory"};
            gameHH = new String[]{"Inventory", "Inventory"};
            gameHI = new String[]{"Shop", "Book Store", "Fashion Store", "Clan Store"};
            gameHK = new String[]{"Split Stone", "Inventory"};
            gameHL = new String[]{"Trade", "Inventory"};
            gameHM = new String[]{"Upgrade essence", "Inventory"};
            gameHN = new String[]{"Add attributes", "Inventory"};
            gameHO = new String[]{"Enhance equipment", "Inventory"};
            gameHP = new String[]{"Socketing", "Inventory"};
            gameHQ = new String[]{"Leveling gem", "Inventory"};
            gameHS = new String[]{"Gem Roasting", "Inventory"};
            gameHT = new String[]{"Extract gem", "Inventory"};
            gameHR = new String[]{"Completed quest", "Inventory"};
            gameXN = new String[]{"Pickup", "Inventory"};
            var10000 = new String[]{"Del", "Inventory"};
            gameXO = "Delete";
            gameXP = "Add";
            gameAU = "I will help decrease bad options of this gem.";
            gameAV = "I will help you extract gem from this item.";
            gameHU = new String[]{"- Use kin incase not enough coin", "- Move to inventory to choose stone", "- Amount of stones from 2 to 24"};
            gameHV = new String[]{"- Use coin incase not enough kin", "- Upgrading need Gold bar", "- Choose Equiptment and stone only", "Your equipment has reached max level"};
            gameHW = new String[]{"- Use coin incase not enough kin", "- Choose Equiptment and Gem"};
            gameHX = "Lock Transfer";
            gameHY = "- Train Stone to level";
            gameHZ = "- Need: # kin";
            gameKA = "- Need: # Gold bars";
            gameKB = "- Need: # coins";
            gameKC = "- Percentage of success.";
            gameKD = "(success ";
            gameKE = "Add";
            gameKG = "Locked";
            gameKH = "Killed";
            gameKI = "Arrest Beast";
            gameKJ = "Kill Elitez";
            gameKK = "Kill Chief";
            gameKL = "Protect the child";
            gameKM = "No lock";
            gameKN = "Expires";
            gameKO = "Price: # kin";
            gameKP = "Price: # coins";
            gameKQ = "Price: # clan coins";
            gameKR = "Price: # kin";
            gameKS = "Price: # gold bars";
            gameKT = "Gold bar";
            gameKU = "Do not have";
            gameKV = "Next level: level #";
            gameKW = "Current level: level #";
            gameKX = "Maximum level";
            gameKY = "Reached maximum level";
            gameKZ = "Require: level";
            gameMA = "Class: ";
            gameMB = new String[]{"Main quest", "Sub quest"};
            ME_TASK = "Quest";
            gameMD = "Obtain quest at";
            gameME = "White Side";
            gameMF = "Black Side";
            gameMG = "Neutral";
            gameMH = "team";
            gameMI = "Find team";
            gameMJ = "Your current aggressive points are ";
            gameMK = new String[]{"Friends", "Hostile"};
            gameML = "You are not friends with anyone";
            gameMM = "waiting confirmation";
            gameMN = "added you to friends list";
            gameMO = "You have added";
            gameMP = "to the list";
            gameMQ = "You and";
            gameMR = new String[]{"store", "Myself", "Map", "General", "Exit", "Jewellery", "Feature", "Pharmaceutical Key", "Pharmacy", "Grocery Key", "Grocery", "Strengthen", "Training", "Training key", "Inventory", "Split Equipment", "Area", "Trade", "Message"};
            gameMS = new String[]{"Passive Support", "Active use", "Active use", "Active use", "Active use"};
            gameMT = new String[]{"Character: ", "Agressive: ", "Level: ", "Class: ", "", "HP:", "MP: ", "Speed: ", "Attack: ", "Anti Fire: ", "Anti Ice: ", "Anti Wind: ", "Reduce Pain: ", "Accurate point:", "Dodge ability: ", "Critical: ", "Close combat strike back: ", "Anti chakra: ", "Anti chakra back: ", "Action points: "};
            gameMU = " times";
            gameMV = new String[]{"Genin", "Chunin", "Jounin", "Kage"};
            gameMW = new String[]{"Action point: ", "Weapon Fame: ", "Necklace Fame: ", "Ring Fame: ", "Gems Fame: ", "Charm Fame: ", "Hat Fame: ", "Cloth Fame: ", "Gloves Fame: ", "Pants Fame: ", "Shoes Fame: ", "Accomplish daily quest: ", "Arrest Beast: ", "Read the basic potential book: ", "Read the basic skill book: ", "Clan: ", "Cave time left: ", "Star Fame: ", "Wind Thunder Mooncake: ", "Ice Fire Mooncake: "};
            gameMX = new String[]{"Name: ", "Gender: ", "Hair: "};
            MENUGENDER = new String[]{"Female", "Male"};
            gameMZ = new String[]{"Strength", "Dexterity", "Constitution", "Chakra"};
            gameNA = "You were not killed by anyone.";
            gameNB = "You won #.";
            gameNC = "You lost #.";
            gameND = "Your fight match between you and # is over.";
            gameNE = new String[]{"", "Elitez", "Chief", "Beast"};
            gameNF = " try to kill you";
            gameNG = "Potential point";
            gameNH = "Skill point";
            gameNI = "Not enough MP to use";
            gameNJ = "Only select unlocked items";
            gameNK = "Only select unlocked items that haven't expired";
            gameNL = "Just choose Stones to train";
            gameNM = "Just choose Stone, Equipment and upgrade insurance.";
            gameNN = "Just choose Equipment and conversion items.";
            gameNO = "Can not upgrade";
            gameNP = "Maximum upgrade";
            gameNQ = "Only upgraded item or equipment to split.";
            gameNR = "Items for Trading are full.";
            gameNS = "Amount is Full.";
            gameNT = "Not enough points.";
            gameNU = "Please input added points.";
            gameNV = "You need to input card information.";
            gameNW = "You need to input card value information.";
            gameNX = "You need to enter serial number.";
            gameNY = "You need to enter topup times.";
            gameNZ = "You need to enter a name";
            gamePA = "Enter Points";
            gamePB = "Enter Coins";
            gamePC = "Enter quantity";
            INPUT_NICK = "Username";
            gamePE = "Coin";
            gamePF = "Kin";
            gamePG = "Gold bar";
            gamePH = "Put in inventory";
            gamePI = "Do you really want to dismissed this one?";
            gamePJ = "Expulsion of members will reduce Clan budgets (see details in Kanata NPC). Do you want to dismiss them?";
            gamePK = "Leaving clan will reduce your coins (see Kanata for details.)  Are you sure you want to leave?";
            gamePL = "After using this item, it will be locked. Do you want to use it?";
            gamePM = "Sold items can not be recovered. Do you want to sell this item?";
            gamePN = new String[][]{{"cap"}, {"wea", "pon"}, {"cloth"}, {"neck", "lace"}, {"glo", "ves"}, {"ring"}, {"pants"}, {"gems"}, {"shoes"}, {"charm"}, {"pet"}, {"mask"}, {"ninja", "yoroi"}, {"clan", "item"}, {"Emp", "ty"}, {"Ancient", "Book"}, {"Ar", "mor"}, {"Sad", "dle"}, {"Tas", "sels"}, {"Coro", "net"}, {"Eng", "ine"}, {"Sat", "nav"}, {"ECU", ""}, {"N20", ""}};
            gamePO = new String[]{"Not a student", "School: Hirosaki", "School: Ookaza", "School: Haruna"};
            gamePP = new String[]{"", "Attribute: Fire", "Attribute: Water", "Attribute: Wind", "", "", ""};
            gamePQ = "You got";
            gamePR = "You have not entered the amount of gold bars.";
            gamePS = "Can not sell upgraded equipment.";
            gamePT = "You don't have enough coins to move.";
            gamePU = "You don't have enough coins to store.";
            gamePV = "You don't have enough coins to withdraw.";
            gamePW = "You don't have enough gold bars to sell.";
            gamePX = new String[]{"Success,  equipped with level up ", "failed, return level of equipment", "equipment upgraded maximum", "equipment level"};
            gamePY = new String[]{"Success socketing", "Socketing has failed"};
            MONTH = "month";
            WEEK = "week";
            DAY = "day";
            HOUR = "hour";
            gameQD = "second";
            MINUTE = ",minute";
            gameQF = "Number of target";
            gameQG = "Range";
            gameQH = "MP cost";
            gameQI = "Cool down time";
            gameQJ = "You need at least two stones to train.";
            gameQK = "Gender does not match";
            gameQL = "Don't have any one else";
            gameQM = "Your level is too low";
            gameQN = "Stone has reached the maximum level";
            gameQO = "Your stones after leveling will be blocked. Would you like to continue?";
            gameQP = "You don't have enough coins to level stone";
            gameQQ = "You don't have enough gold bars to upgrade equipment";
            gameQR = "You don't have enough coins to upgrade equipment";
            gameQS = "Many training stones will be wasted. Are you sure you want to upgrade";
            gameQT = "After upgrade this item will be locked. Do you want to continue?";
            gameQU = "Can not split the unupgraded item.";
            gameQV = "Your luggage doesn't have enough space.";
            gameQW = "Do you really want to split this item?";
            gameQX = "Do you really want to convert?";
            gameQY = "Welcome to trading. Do you want to trade?";
            gameQZ = "Welcome to the clan. Do you want to join Clan '#' ?";
            gameRA = "Do you want to join this clan?";
            gameRB = "wants to fight with you. Do you accept?";
            gameRD = "invite you to Party. Do you want to join?";
            gameRE = "ask you to join their Party. Do you accept?";
            gameRF = "Convert successful.";
            gameRG = new String[]{"Gender: Female", "Gender: Male"};
            gameRH = "Area";
            gameRI = "Population";
            gameRJ = "Party";
            gameRK = "At this moment, you have not joined any Party.";
            gameRL = "times";
            gameRM = new String[]{"Info", "Member", "Warehouse", "Statistic", "Guardian"};
            gameRN = new String[]{"Clan: ", "Clanmaster: ", "Member: ", "Level: ", "Experience: ", "Budget: ", "Establish: ", "Donation: ", "Maintenance fee: ", "Upgrade fee: ", "Enter the Territory of Clan: remain ", "Week donation: ", "Use Clan card mark: remain "};
            CLAN_ACTIVITY = new String[]{"Coins at", "Establish clan, budget has", "expulsion, budget decrease", "clan contribution, budget increase", "withdraw clan budget, budget decrease", "Fee for maintain clan, budget decrease", "upgrade clan, budget decrease"};
            gameRP = "You are not a member of any clan";
            gameRQ = "Send to Clan Member";
            gameRR = new String[][]{{"Hirosaki School"}, {"Haruna School"}, {"Ookaza School"}, {"Village", "Kojin village", "Sanzu village", "Tone village", "Fish Village", "Chakumi Village", "Echigo Village", "Oshin Village"}, {"Area"}};
            gameRS = new String[]{"Cap", "Ring", "Cloth", "Necklace", "Gloves", "Ring", "Pants", "Gems", "Shoes", "Charm"};
            gameRT = new String[]{"Active hidden", "Active level"};
            gameRU = new String[]{"", "Fire", "Water", "Wind"};
            CHARINGFO = new String[]{"Character", "Level", "Jewellery"};
            gameRW = "You do not have any special skills.";
            gameRX = "You do not have any special weapons. Go to Menu/Status/Equipment to check";
            gameRY = "This item was locked.";
            gameRZ = "Items, accessories and stones";
            gameSA = "price (coin)";
            gameSB = "price (kin)";
            gameSC = "You are hungry, eat some more";
            gameSD = "You level is too low to use this item";
            gameSE = "Out off MP";
            gameSF = "Out off HP";
            gameSG = new String[]{"Trade", "Fight", "Berserker", "Add friend", "Invite to Party", "Recover", "Check info", "Private chat", "Invite to clan", "Request to join clan", "Block request to joint clan", "Auto recover", "Cấm Chat"};
            gameSH = "You are in ";
            gameSI = new String[]{"Let's find", " at ", " to get the quest.", "You have finished all quests this version, please wait for the next version."};
            gameSJ = new String[]{"Exhausted", "Starring", "Come back", "Revive now (1 Gold bar)"};
            gameSK = "After joining a class, you can receive any quest from the principal.";
            gameSL = "Create team";
            gameSM = "Leave team";
            gameSN = "Teamleader";
            gameSO = "Lock team";
            gameSP = "Unlock team";
            gameSQ = "Ask to join party.";
            gameSR = "Refresh";
            gameSS = "You are not a member of any team.";
            gameST = "Empty information.";
            gameSU = "Cannot find any Party now.";
            gameSV = new String[]{"PK normal", "PK team", "PK clan", "PK Berserker"};
            gameSW = new String[]{"PK status", "Friend", "Enemy", "Party", "Find party", "Clan", "Protect account", "Auto", "Sell Shinwa", "Upgrade essence", "Enhance equipment", "Add attributes"};
            gameSX = new String[]{"Map", "Quest", "Clan"};
            gameSY = new String[]{"Clan Master", "Chief Elder", "Elder", "Elite", "Member"};
            gameSZ = new String[]{"(CM)", "(CE)", "(ED)", "(EL)"};
            gameTA = new String[]{"Online only", "Left", "Notice ", " Contribute ", " Withdraw funds ", " Upgrade ", " Invite to territory ", "Unlock"};
            gameTB = "Sort by dedicating week";
            gameTC = new String[]{"Expulsion", "Transfer", "Make friend"};
            gameTD = " You are promoted to team leader.";
            gameTE = "You were kicked off of team.";
            gameTF = "Invite to team";
            gameTG = "Add";
            gameTH = "Inappropriated Weapons.";
            gameTI = "Do you want to delete this person from your friend list?";
            gameTJ = new String[]{"Go to school to upgrade your marks."};
            gameTK = new String[]{"Strength = Attack", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = MP"};
            gameTL = new String[]{"No need to upgrade strength", "Dexterity = dodge, accurate", "Strength = HP", "Chakra = Attack, MP"};
            CLOSE_CURTAB = "Close current tab.";
            PUBLICCHAT = new String[]{"Public chat", "You can chat with people around you here."};
            PARTYCHAT = new String[]{"Same party", "You can chat with your Party member here."};
            GLOBALCHAT = new String[]{"Global chat", "You will lose 5 Gold Bars for each use.", "This message will broadcast to everybody.", "Your account will automatically be locked if you attempt to advestise any wap website, or use profanity."};
            CLANCHAT = new String[]{"Clan", "Yon can chat with Clanmates in this place"};
            gameTR = "Block global chat: ";
            gameTS = "Block private chat: ";
            gameTT = "Appoint";
            gameTU = "Dismiss";
            gameTV = "Expulsion";
            gameTW = "Maximum 6 digits.";
            gameTX = "Just allow number digit for protected password.";
            gameTY = "Protected password can not start with number 0.";
            gameTZ = "Wrong password.";
            gameUA = "To use this function, you have to have Multi Teleport Card.";
            gameUB = "To activate this function, you have to pay 10.000 kin. Do you want to activate?";
            gameUC = "Password";
            gameUD = "input the mobile number that you want to register";
            gameUE = "You did not input the number that you used to register this game before.";
            gameUF = "To get the password for account '#'. You must use the phone number used to register this account.";
            gameUG = "Change pass";
            gameUH = "Cancel protection";
            gameUI = "Old password";
            gameUJ = "New password";
            gameUK = "You have learned ";
            gameUL = "Input your message content";
            gameUM = "Input the amount of coin to withdraw";
            gameUN = "Input the coin amount to donate to the Clan.";
            gameUO = "Input type of card and value";
            gameUP = "Input serie number and time of charging.";
            gameUQ = "Input amount of split time.";
            gameUR = "Value";
            gameUS = "Type of card";
            gameUT = "Seri number";
            gameUU = "Time of charging";
            gameUV = "Block message";
            gameUW = "Submit this bug to Admin.";
            gameUX = new String[]{"Assign key", "Assign to 5 key"};
            gameUY = "Send message success.";
            gameUZ = "Congratulations! your choice is correct.";
            gameVA = "Can not send message.";
            gameVB = "Send failure.";
            gameVC = "Not enough coin to contribute";
            gameVD = "The amount to split is invalid.";
            gameVE = "invalid input value.";
            gameVF = "Do you want to cancel Protect account function?";
            gameRC = "wants to challenge you in the battle arena. Do you agree?";
            gameVG = "Sort by price";
            gameVH = "Sort by level";
            gameVI = "Sort by name";
            gameVJ = "Item is sent for trading";
            gameVK = "Trading fee is 5.000 coin";
            gameVM = "Do you want to sell item with # coins ?";
            gameVN = "Do you want to buy item with # coins ?";
            gameVO = "Seller";
            gameVP = "remain";
            gameVQ = "a few";
            gameVR = "seconds";
            gameVS = new String[]{"Stone", "Cap", "Weapon", "Cloth", "Necklace", "Gloves", "Rings", "Cloths", "Gems", "Shoes", "Charms", "Miscellaneous"};
            gameVL = "pay 1% of value as tax";
            gameKF = "Experience";
            gameVT = "Announcement";
            gameVU = "Invite friends";
            gameVV = "Choose card";
            gameVW = "Flip remaining: ";
            gameVX = "Challenges you and your clan. Do you agree ?";
            gameVY = "Max options";
            gameVZ = "Invite this person";
            gameWA = "Invite all";
            gameWB = "'#' invites you to join the clan war. Do you want to join?";
            gameWC = "Input member's name";
            gameWD = new String[][]{{"Requirement: Clan level 5", "Cost to Open: 1.000.000 clan coins."}, {"Requirement: Clan level 10.", "Cost to Open: 5.000.000 clan coins."}, {"Requirement: Clan level 15.", "Cost to Open: 10.000.000 clan coins."}, {"Requirement: Clan level 20.", "Cost to Open: 20.000.000 clan coins."}, {"Requirement: Clan level 25.", "Cost to Open: 30.000.000 clan coins."}};
            gameWE = new String[]{"HP: ", "MP: ", "Using food level: ", "Always using skill to support", "Dùng khiên mana", "Dùng đốt quái", "Dùng phân thân", "Pick up Kins", "Pick up Hp, MP", "Pick up Material", "Luyện đá Max", "Nhặt Trang Bị", "Nhặt Trang Bị Lạ", "Nhặt VP Nhiệm Vụ", "Nhặt VP Sự Kiện", "Nhặt All", "Nhặt SVC", "Not picked up", "Auto TTT", "AutoTTC", "ReMap", "Tàn sát map trống", "Auto Mua Thức Ăn", "TS khi hết MP", "Auto Reconnect", "Next Map Null Boss", "Săn TATL", "Hit Normal", "Hit Elitez", "Hit Chief", "Cộng tiềm năng", "Cộng kĩ năng", "Đánh theo nhóm", "Né PK","Dùng Cổ Lệnh","Mua Cổ Lệnh"};
            gameWF = "Use button < and > to change value";
            gameWG = "Touch to change value";
            gameWH = "Distance is very far, Can not heal another people";
            gameWI = "Percent value is from 10 to 90";
            gameWJ = new String[]{"Level 1", "Level 10", "Level 20", "Level 30", "Level 40", "Level 50", "Level 60", "Level 70"};
            gameWK = new String[]{"Level 1", "Level 2", "Level 3", "Level 4", "Level 5", "Level 6", "Level 7", "Level 8", "Level 9", "Level 10", "Level 11", "Level 12"};
            gameWL = "Account required password, input password to unlock.";
            gameWM = "Vitality";
            gameWN = "Name of mounts";
            gameWO = new String[]{"Upgrade essence by using 9 essences", "of the same kind or 3 common essences", "and stone level 11 or 3 rare essences and stone level 12."};
            gameWP = "Only common essence and rare essence";
            gameWQ = "Only stone and essence to upgrade essence";
            gameWR = "Just only 1 stone to upgrade";
            gameWS = "Need to use 3 rare essences and stone level 12 or 3 common essences and stone level 11";
            gameWT = "Have to use stone level 11 and 12";
            gameWU = "Have to use essences of the same kind";
            gameWV = "Have to has 3 essences to Upgrade";
            gameWW = "Essences are excessive";
            gameWX = "This equipment can not Enhance";
            gameWY = "Not enough material";
            gameWZ = "This function is not available for this equipment";
            gameXA = "Save candy";
            gameXB = "Enhance level";
            gameXC = "Engine";
            gameXD = "Fuel";
            gameXE = "Give candy";
            gameXF = new String[]{"essence", "essence", "common essences", "rare essences"};
            gameXG = "Equipment enhanced to max level already";
         }

      }
   }

   public static String gameAA(String var0, String var1) {
      return NinjaUtil.gameAA(var0, "#", var1);
   }
}
